DefaultSNI: www.baidu.com
Entry:
  - name: Steam
    hosts:
      - api.steampowered.com
      - store.steampowered.com
      - steamusercontent-a.akamaihd.net
      - steam-chat.com
      - steamcommunity.com
    enable: true
    group: steam
  - name: Github
    hosts:
      - github.com
      - raw.githubusercontent.com
    group: github
    enable: true
    upstream: 
      - 151.101.192.133
      - 151.101.64.133
  - name: Pivix
    hosts:
      - www.pixiv.net
      - touch.pixiv.net
      - source.pixiv.net
      - accounts.pixiv.net
      - imgaz.pixiv.net
      - app-api.pixiv.net
      - oauth.secure.pixiv.net
      - dic.pixiv.net
      - comic.pixiv.net
      - factory.pixiv.net
      - g-client-proxy.pixiv.net
      - sketch.pixiv.net
      - payment.pixiv.net
      - sensei.pixiv.net
      - novel.pixiv.net
      - ssl.pixiv.net
      - times.pixiv.net
      - recruit.pixiv.net
      - pixiv.net
      - p2.pixiv.net
      - matsuri.pixiv.net
      - m.pixiv.net
      - iracon.pixiv.net
      - inside.pixiv.net
      - i1.pixiv.net
      - help.pixiv.net
      - goods.pixiv.net
      - genepixiv.pr.pixiv.net
      - festa.pixiv.net
      - en.dic.pixiv.net
      - dev.pixiv.net
      - chat.pixiv.net
      - blog.pixiv.net
      - embed.pixiv.net
      - comic-api.pixiv.net
      - pay.pixiv.net
    enable: true
    upstream:
      - pixiv.rmbgame.net
  - name: discord
    hosts:
      - discord.com
      - discordapp.com
      - dl.discordapp.net
      - gateway.discord.gg
      - status.discordapp.com
      - cdn.discordapp.com
      - media.discordapp.net
      - images-ext-2.discordapp.net
      - images-ext-l.discordapp.net
      - discordcdn.com
    enable: true
    group: discord
UpstreamGroups:
  steam:
    - steamcommunity.rmbgame.net
    - steamuserimages-a.akamaihd.net
    - steamstore-a.akamaihd.net
    - steamcommunity-a.akamaihd.net
    - eaassets-a.akamaihd.net
    - humblebundle-a.akamaihd.net
    - steamcommunity-a.akamaihd.net
    - 23.10.1.33
    - 23.2.38.204
    - 23.59.133.245
    - 23.77.75.2
    - 23.78.144.143
    - 184.24.4.13
    - 23.39.21.31
    - 104.105.240.155
    - 104.77.69.164
    - 23.66.175.84
    - 184.51.205.49
    - 184.86.38.254
    - 96.16.130.74
    - 23.198.91.12
    - 23.213.218.250
    - 104.86.15.75
  github:
    - 13.234.210.38
    - 13.234.176.102
    - 52.69.186.44
    - 52.192.72.89
    - 52.78.231.108
    - 13.114.40.48
    - 192.30.266.113
    - 140.82.112.3
    - 140.82.112.4
    - 140.82.114.4
    - 52.74.223.119
    - 13.229.188.59
    - 140.82.113.4
    - 13.260.177.223
    - 140.82.121.4
    - 192.30.255.112
    - 140.82.114.3
  discord:
    - 162.159.130.233
    - 104.20.160.100
    - 104.22.0.100
    - 103.21.244.100
    - 104.20.160.5
    - 104.17.128.100
    - 104.20.96.100
    - 104.22.64.100
    - 104.20.159.5
    - 1.0.0.1
    - 104.16.0.100
    - 104.16.192.100
    - 104.17.64.100
    - 104.17.192.100
    - 104.18.160.100
    - 104.19.224.100
    - 172.67.160.100
    - 172.67.192.100
  pixiv:
    - pximg.rmbgame.net